#!/bin/bash

export SERVERMODE="PROD"

NEWVERSION=$1
DEPLOYCOPY=$2
DEPLOYDEST=$3
DEPLOYPROJECTNAME=$4
DEPLOYFILENAME=$5

DEPLOYOUTPUTDIR=${DEPLOYPROJECTNAME}_${NEWVERSION}

cd ${DEPLOYCOPY}
cp -f ./${DEPLOYFILENAME} ${DEPLOYDEST}
cd ${DEPLOYDEST}
mkdir -p ${DEPLOYOUTPUTDIR}
tar -zxvf ./${DEPLOYFILENAME} -C ${DEPLOYOUTPUTDIR}
cd ./${DEPLOYOUTPUTDIR}

make

