#!/bin/bash

NEWVERSION=$1
DEPLOYCOPY=$2
DEPLOYDEST=$3
DEPLOYPROJECTNAME=$4
DEPLOYFILENAME=$5
DEPLOYMODE=$6

DEPLOYOUTPUTDIR=${DEPLOYPROJECTNAME}_${NEWVERSION}

cd ${DEPLOYCOPY}
cp -f ./${DEPLOYFILENAME} ${DEPLOYDEST}
cd ${DEPLOYDEST}
mkdir -p ${DEPLOYOUTPUTDIR}
tar -zxvf ./${DEPLOYFILENAME} -C ${DEPLOYOUTPUTDIR}
ln -sf ./${DEPLOYOUTPUTDIR} ./current
#cd ./${DEPLOYOUTPUTDIR}
cd ./current

if [ ${DEPLOYMODE} = "PRODUCTION" ]; then
	make DEPLOYOUTPUTDIR=${DEPLOYDEST}/current PRODUCTION="TRUE"
elif [ ${DEPLOYMODE} = "PRELEASE" ]; then
	make DEPLOYOUTPUTDIR=${DEPLOYDEST}/current PRELEASE="TRUE"
fi

